from datetime import datetime
from typing import Dict

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>FinOps Report — {date}</title>
<style>
  body{{font-family:system-ui,sans-serif;max-width:960px;margin:40px auto;color:#1a1a2e}}
  h1{{color:#16213e}}h2{{color:#0f3460;border-bottom:2px solid #e94560;padding-bottom:8px}}
  .kpi{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}}
  .kpi-card{{background:#f8f9fa;border-radius:8px;padding:20px;text-align:center;border-left:4px solid #e94560}}
  .kpi-value{{font-size:2rem;font-weight:700;color:#e94560}}
  .kpi-label{{font-size:.85rem;color:#666;margin-top:4px}}
  table{{width:100%;border-collapse:collapse;margin:16px 0}}
  th{{background:#16213e;color:white;padding:10px 12px;text-align:left}}
  td{{padding:9px 12px;border-bottom:1px solid #eee}}
  tr:hover td{{background:#f5f5f5}}
  .badge{{display:inline-block;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600}}
  .red{{background:#ffe0e0;color:#c0392b}}.amber{{background:#fff3cd;color:#856404}}
  footer{{margin-top:48px;text-align:center;color:#888;font-size:.85rem}}
</style></head>
<body>
  <h1>💰 FinOps Cost Report</h1>
  <p>Account: <strong>{account}</strong> · Period: <strong>{period}</strong> · {date}</p>
  <div class="kpi">
    <div class="kpi-card"><div class="kpi-value">${total:,.0f}</div><div class="kpi-label">Total Spend</div></div>
    <div class="kpi-card"><div class="kpi-value">${waste:,.0f}</div><div class="kpi-label">Identified Waste</div></div>
    <div class="kpi-card"><div class="kpi-value">{pct:.1f}%</div><div class="kpi-label">Waste %</div></div>
    <div class="kpi-card"><div class="kpi-value">${annual:,.0f}</div><div class="kpi-label">Annual Savings</div></div>
  </div>
  <h2>Top Savings Opportunities</h2>
  <table><tr><th>#</th><th>Resource</th><th>Type</th><th>Action</th><th>Monthly Saving</th></tr>
  {rows}</table>
  <footer>Generated by <a href="https://github.com/ashwani547/finops-cloud-cost-optimizer">finops-cloud-cost-optimizer</a></footer>
</body></html>"""

class HTMLReporter:
    def generate(self, summary: Dict, output_path: str) -> str:
        rows = ""
        for i, item in enumerate(summary.get("top_offenders", []), 1):
            cls = "red" if item["waste_usd"] > 500 else "amber"
            rows += (f"<tr><td>{i}</td><td><code>{item['id']}</code></td>"
                     f"<td>{item['type']}</td>"
                     f"<td><span class='badge {cls}'>{item['action']}</span></td>"
                     f"<td><strong>${item['waste_usd']:,.2f}</strong></td></tr>")
        total = summary.get("total_spend_usd", 0)
        waste = summary.get("total_monthly_waste_usd", 0)
        html  = TEMPLATE.format(
            date=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
            account=summary.get("account", "N/A"), period=summary.get("period", "Last 30 days"),
            total=total, waste=waste,
            pct=(waste/total*100 if total else 0),
            annual=summary.get("total_annual_waste_usd", 0), rows=rows,
        )
        with open(output_path, "w") as f:
            f.write(html)
        return output_path
