"""Generates a styled HTML cost savings report."""
from __future__ import annotations
from datetime import datetime
from typing import Dict

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>FinOps Cost Report — {date}</title>
  <style>
    *{{box-sizing:border-box;margin:0;padding:0}}
    body{{font-family:system-ui,sans-serif;background:#f0f2f5;color:#1a1a2e;padding:32px 16px}}
    .wrap{{max-width:1000px;margin:0 auto}}
    h1{{font-size:1.8rem;color:#16213e;margin-bottom:4px}}
    .sub{{color:#666;font-size:.9rem;margin-bottom:28px}}
    h2{{font-size:1.1rem;color:#0f3460;border-bottom:2px solid #e94560;padding-bottom:6px;margin:28px 0 14px}}
    .kpi{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px;margin-bottom:28px}}
    .card{{background:#fff;border-radius:10px;padding:20px;text-align:center;
           box-shadow:0 1px 4px rgba(0,0,0,.08);border-top:4px solid #e94560}}
    .val{{font-size:2rem;font-weight:700;color:#e94560}}
    .lbl{{font-size:.8rem;color:#888;margin-top:4px;text-transform:uppercase;letter-spacing:.04em}}
    table{{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;
           overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)}}
    th{{background:#16213e;color:#fff;padding:11px 14px;font-size:.82rem;text-align:left;font-weight:600}}
    td{{padding:10px 14px;border-bottom:1px solid #f0f2f5;font-size:.88rem}}
    tr:last-child td{{border-bottom:none}}
    tr:hover td{{background:#f8f9ff}}
    .badge{{display:inline-block;padding:3px 10px;border-radius:20px;font-size:.75rem;font-weight:600}}
    .red{{background:#ffe0e0;color:#b91c1c}}
    .amber{{background:#fef3c7;color:#92400e}}
    .green{{background:#d1fae5;color:#065f46}}
    footer{{margin-top:40px;text-align:center;color:#aaa;font-size:.8rem}}
    a{{color:#e94560}}
  </style>
</head>
<body>
<div class="wrap">
  <h1>💰 FinOps Cost Report</h1>
  <p class="sub">Account: <strong>{account}</strong> &nbsp;·&nbsp; Period: <strong>{period}</strong> &nbsp;·&nbsp; Generated: {date}</p>

  <div class="kpi">
    <div class="card"><div class="val">${total_spend:,.0f}</div><div class="lbl">Total Spend</div></div>
    <div class="card"><div class="val">${waste_usd:,.0f}</div><div class="lbl">Identified Waste</div></div>
    <div class="card"><div class="val">{waste_pct:.1f}%</div><div class="lbl">Waste %</div></div>
    <div class="card"><div class="val">${annual_savings:,.0f}</div><div class="lbl">Annual Savings Est.</div></div>
  </div>

  <h2>Top Savings Opportunities</h2>
  <table>
    <tr><th>#</th><th>Resource ID</th><th>Type</th><th>Cloud</th><th>Action</th><th>Monthly Saving</th></tr>
    {rows}
  </table>

  <footer>
    Generated by
    <a href="https://github.com/ashwani547/finops-cloud-cost-optimizer">finops-cloud-cost-optimizer</a>
    &nbsp;·&nbsp; Ashwani Kumar
  </footer>
</div>
</body>
</html>"""


class HTMLReporter:
    def generate(self, summary: Dict, output_path: str) -> str:
        offenders = summary.get("top_offenders", [])
        rows = ""
        for i, item in enumerate(offenders, 1):
            w = item["waste_usd"]
            cls = "red" if w > 500 else ("amber" if w > 100 else "green")
            rows += (
                f"<tr><td>{i}</td><td><code>{item['id']}</code></td>"
                f"<td>{item['type']}</td><td>{item.get('cloud', 'aws')}</td>"
                f"<td><span class='badge {cls}'>{item['action']}</span></td>"
                f"<td><strong>${w:,.2f}</strong></td></tr>"
            )
        total  = summary.get("total_spend_usd", 0) or 1
        waste  = summary.get("total_monthly_waste_usd", 0)
        html   = TEMPLATE.format(
            date=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
            account=summary.get("account", "N/A"),
            period=summary.get("period", "Last 30 days"),
            total_spend=total,
            waste_usd=waste,
            waste_pct=waste / total * 100,
            annual_savings=summary.get("total_annual_waste_usd", 0),
            rows=rows,
        )
        with open(output_path, "w") as fh:
            fh.write(html)
        return output_path
